debug: true
fly-animation: flying

bees:
  - type: redstone-bee
    model-id: 1
    display-name: <red>Redstone Bee
    foods:
      - REDSTONE
    flowers:
      - REDSTONE_BLOCK
    product:
      additional:
        material: REDSTONE_ORE
      honey:
        material: HONEYCOMB
        name: Redstone Honeycomb
        lore:
          - This is a redstone honeycomb
      honey-block:
        material: HONEYCOMB_BLOCK
        name: Redstone Honey Block
        lore:
          - This is a redstone honey block
    model: redstone-bee

  - type: emerald-bee
    display-name: <green>Emerald Bee
    foods:
      - EMERALD
    flowers:
      - EMERALD_BLOCK
    product:
      additional:
        material: EMERALD_ORE
      honey:
        material: HONEYCOMB
        name: Emerald Honeycomb
        lore:
          - This is an emerald honeycomb
      honey-block:
        material: HONEYCOMB_BLOCK
        name: Emerald Honey Block
        lore:
          - This is an emerald honey block

  - type: diamond-bee
    display-name: <aqua>Diamond Bee
    foods:
      - DIAMOND
    flowers:
      - DIAMOND_BLOCK
    product:
      additional:
        material: DIAMOND_ORE
      honey:
        material: HONEYCOMB
        name: Diamond Honeycomb
        lore:
          - This is a diamond honeycomb
      honey-block:
        material: HONEYCOMB_BLOCK
        name: Diamond Honey Block
        lore:
          - This is a diamond honey block

  - type: gold-bee
    display-name: <gold>Gold Bee
    foods:
      - GOLD_INGOT
    flowers:
      - GOLD_BLOCK
    product:
      additional:
        material: GOLD_ORE
      honey:
        material: HONEYCOMB
        name: Gold Honeycomb
        lore:
          - This is a gold honeycomb
      honey-block:
        material: HONEYCOMB_BLOCK
        name: Gold Honey Block
        lore:
          - This is a gold honey block

  - type: iron-bee
    display-name: <gray>Iron Bee
    foods:
      - IRON_INGOT
    flowers:
      - IRON_BLOCK
    product:
      additional:
        material: IRON_ORE
      honey:
        material: HONEYCOMB
        name: Iron Honeycomb
        lore:
          - This is an iron honeycomb
      honey-block:
        material: HONEYCOMB_BLOCK
        name: Iron Honey Block
        lore:
          - This is an iron honey block

bee-box:
  material: PAPER
  name: Bee box
  lore:
    - This is a beebox
    - '%bees%'

bee-box-size: 10

bee-jar:
  material: GLASS_BOTTLE
  name: Bee jar
  lore:
    - This is a bee jar
    - '%bee%'

beehive-lore:
  - This is a beehive patch
  - You can use it to patch your beehive
  - It will add a new lore to your beehive
  - 'production multiplier: %production-multiplier%'
  - 'produce-blocks: %produce-blocks%'
  - 'max-bees: %max-bees%'
